# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "BLOG_ENTRY" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"title" VARCHAR NOT NULL,"content" VARCHAR NOT NULL,"date" DATE NOT NULL,"author" BIGINT NOT NULL);
create table "BLOG_ENTRY_COMMENT" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"from" BIGINT NOT NULL,"to" BIGINT NOT NULL);
create table "BLOG_ENTRY_TOPIC" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"from" BIGINT NOT NULL,"to" BIGINT NOT NULL);
create table "COMMENT" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"author" VARCHAR NOT NULL,"email" VARCHAR NOT NULL,"date" DATE NOT NULL,"comment" VARCHAR NOT NULL);
create table "TOPIC" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"title" VARCHAR NOT NULL);
create table "USER" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"username" VARCHAR NOT NULL,"email" VARCHAR NOT NULL,"password" VARCHAR NOT NULL,"lastlogin" DATE);
alter table "BLOG_ENTRY_COMMENT" add constraint "blog_entry_comment_fromFk" foreign key("from") references "BLOG_ENTRY"("id") on update NO ACTION on delete CASCADE;
alter table "BLOG_ENTRY_COMMENT" add constraint "blog_entry_comment_toFk" foreign key("to") references "COMMENT"("id") on update NO ACTION on delete CASCADE;
alter table "BLOG_ENTRY_TOPIC" add constraint "blog_entry_topic_fromFk" foreign key("from") references "BLOG_ENTRY"("id") on update NO ACTION on delete CASCADE;
alter table "BLOG_ENTRY_TOPIC" add constraint "blog_entry_topic_toFk" foreign key("to") references "TOPIC"("id") on update NO ACTION on delete CASCADE;

# --- !Downs

alter table "BLOG_ENTRY_COMMENT" drop constraint "blog_entry_comment_fromFk";
alter table "BLOG_ENTRY_COMMENT" drop constraint "blog_entry_comment_toFk";
alter table "BLOG_ENTRY_TOPIC" drop constraint "blog_entry_topic_fromFk";
alter table "BLOG_ENTRY_TOPIC" drop constraint "blog_entry_topic_toFk";
drop table "BLOG_ENTRY";
drop table "BLOG_ENTRY_COMMENT";
drop table "BLOG_ENTRY_TOPIC";
drop table "COMMENT";
drop table "TOPIC";
drop table "USER";

